---
## # ERROR: with_items is not a legal parameter in an Ansible Playbook
## # -----------------------------------------------------------------
## # Therefore I do the same thing twice, once for masters, once for slaves
# ensure masters have proper config
- hosts: mysqlmasters
  user: ubuntu
  sudo: True
  vars_files:
   - ./variables-masters.yml
   - ../PalominoClusterToolConfig.yml
  tasks:
   - name: Setup MySQL Configuration for masters
     action: template src=templates/my.cnf dest=/etc/mysql/my.cnf owner=mysql mode=0644
# ensure slaves have proper config
- hosts: mysqlslaves
  user: ubuntu
  sudo: True
  vars_files:
   - ./variables-slaves.yml
   - ../PalominoClusterToolConfig.yml
  tasks:
   - name: Setup MySQL Configuration for slaves
     action: template src=templates/my.cnf dest=/etc/mysql/my.cnf owner=mysql mode=0644


## # if ever with_items is a legal parameter in Ansible Playbook
## # -----------------------------------------------------------
## # ensure masters/slaves both have proper config
## - hosts: mysql$item
##   user: ubuntu
##   sudo: True
##   vars_files:
##    - ./variables-$item.yml
##    - ../PalominoClusterToolConfig.yml
##   tasks:
##    - name: Setup MySQL Configuration for $item
##      action: template src=templates/my.cnf dest=/etc/mysql/my.cnf owner=mysql mode=0644
## 
##      # my.cnf post-processing
##    - name: Remove default settings from MySQL Configuration for $item
##      action: command /usr/local/bin/fixMySQLconfig.pl /etc/mysql/my.cnf
## 
##    - name: Bounce mysqld - TODO - Convert to handler only do if my.cnf changed
##      action: service name=mysql state=restarted
##   with_items:
##    - masters
##    - slaves


- hosts: mysqlmasters:mysqlslaves
  user: ubuntu
  sudo: True
  vars_files:
   - ../PalominoClusterToolConfig.yml
  tasks:
   - name: Post-process MySQL Configuration
     action: command /usr/local/bin/fixMySQLconfig.pl /etc/mysql/my.cnf

   - name: Bounce mysqld - TODO - Convert to handler only do if my.cnf changed
     action: service name=mysql state=restarted

