---
# create a replication user on the master for the slaves
# to connect to
- hosts: mysqlmasters
  user: ubuntu
  sudo: True
  vars_files:
   - ../PalominoClusterToolConfig.yml
  tasks:
   - name: create replication user on masters
     action: shell echo "grant replication slave on *.* to "${repl_user}"@'%' identified by '"${repl_password}"';" | mysql -uroot


# execute a CHANGE MASTER on all slaves
- hosts: mysqlslaves
  user: ubuntu
  sudo: True
  vars_files:
   - ../PalominoClusterToolConfig.yml
  tasks:
   - name: slave all slaves to the master
     action: shell creates=/var/run/palominoReplicationTopologySet.ansible /usr/local/bin/generateChangeMasterSQL.pl ${master_host} ${repl_user} ${repl_password} | mysql -uroot > /var/run/palominoReplicationTopologySet.ansible 2>&1

