---
# just copy some files into place
- hosts: palominoclusternodes
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
  tasks:
   - name: Copy generic helper scripts onto managed node
     action: copy src=../files/$item dest=/usr/local/bin/$item mode=0755
     with_items:
      - fixAptKeys.sh

   # sources.list should point to only our repo - TODO: can we remove this?
   - name: Create /etc/apt/sources.list with only our internal server
     action: template src=../templates/etc:apt:sources.list dest=/etc/apt/sources.list owner=root

   # uncomment this if you use public repos - TODO: can we remove this?
   - name: Ensure apt repo has all missing keys
     action: command /usr/local/bin/fixAptKeys.sh creates=aptKeysFixed

   # do apt-get update across the cluster - so subsequent playbooks don't have to
   - name: do apt-get update across the cluster
     action: command /usr/bin/apt-get update

