---
# on all hosts, install required software
- hosts: mysqlmasters:mysqlslaves
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
  tasks:
   - name: Copy Configuration postprocessing scripts
     action: copy src=../files/$item dest=/usr/local/bin/$item owner=root mode=0755
     with_items:
      - fixMySQLconfig.pl
      - fixMySQLulimits.pl
      - generateChangeMasterSQL.pl

   # pigz needed by Jetpants
   - name: Install MysQL and connector libraries - force/update_cache are on-purpose
     action: apt name=$item state=installed force=yes update_cache=yes
     with_items:
      - mysql-server-5.5
      - python-mysqldb
      - libdbd-mysql-perl
      - libdbi-perl
      - pigz

   - name: Give MySQL user proper limits
     action: command /usr/local/bin/fixMySQLulimits.pl /etc/security/limits.conf /etc/pam.d/common-session

