---
# this will propogate via replication to the slaves - hence we only
# do it on mysqlmasters
- hosts: mysqlmasters
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
  tasks:
   - name: create Zabbix user on databases
     action: mysql_user name=$mysql_Zabbix_user  password=$mysql_Zabbix_password  host=%  priv='*.*:super,process'

   - name: create Cacti user on databases
     action: mysql_user name=$mysql_Cacti_user  password=$mysql_Cacti_password  host=%  priv='*.*:super,process'

   - name: create Nagios user on databases
     action: mysql_user name=$mysql_Nagios_user  password=$mysql_Nagios_password  host=%  priv='*.*:super,process'

   - name: create read user on databases
     action: mysql_user name=$mysql_read_user  password=$mysql_read_password  host=%  priv='*.*:select'

   - name: create write user on databases
     action: mysql_user name=$mysql_write_user  password=$mysql_write_password  host=%  priv='*.*:select,insert,update,delete,references,create temporary tables,lock tables,execute'
